server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 120.78.187.144:2181
      discovery:
        enabled: true   #是否启用zookeeper
        register: true   #是否注册微服务
